spring.application.name=demo
server.port=8081

spring.datasource.url=jdbc:postgresql://dpg-d7o5t3t7vvec739ib740-a:5432/smart_traffic_system
spring.datasource.username=smart_traffic_system_user
spring.datasource.password=IAdT5T5JSWgkPZOI2doxSB97uBX8u8tZ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
